"$schema" = 'https://starship.rs/config-schema.json'
add_newline = true

format = """
$all
$character"""

[cmd_duration]
min_time = 2000
format = """
$character"""

[character]
success_symbol = "[âœ](bold green)"
error_symbol = "[âœ—](bold red)"

[directory]
truncation_length = 3
truncation_symbol = "â€¦/"
style = "cyan bold"
read_only = "ğŸ”’"
read_only_style = "red"

[git_branch]
symbol = "î‚  "
truncation_length = 20
truncation_symbol = "â€¦"
style = "bold purple"

[git_status]
stashed = "ğŸ“¦ "
modified = "âœï¸ "
staged = "âœ”ï¸ "
deleted = "ğŸ—‘ï¸ "
style = "bold green"

[nodejs]
format = "via [â¬¢ $version](bold green)"
detect_extensions = ["js", "ts"]
detect_files = ["package.json", "node_modules"]

[python]
symbol = "ğŸ "
style = "bold yellow"
format = "via [$symbol$version]($style)"
detect_files = ["requirements.txt", "pyproject.toml", "Pipfile", ".venv"]
pyenv_version_name = false

[aws]
format = "on [â˜ï¸ $profile](bold blue)"
style = "blue bold"
symbol = "â˜ï¸ "

[docker_context]
format = "via [ğŸ³ $context](bold cyan)"
only_with_files = true
style = "cyan bold"

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡"
discharging_symbol = "ğŸ”Œ"
format = "[$symbol$percentage](bold green)"
[[battery.display]]
threshold = 30
style = "bold yellow"
[[battery.display]]
threshold = 10
style = "bold red"

[fill]
symbol = "-"
style = "bold green"

